name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REPOSITORY_OWNER: ${{ github.repository_owner }}
      # Add this to suppress some warnings
      DOCKER_BUILDKIT: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate linting
        
    - name: Convert repository owner to lowercase
      run: echo "REPOSITORY_OWNER=$(echo $REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPOSITORY_OWNER }}/weather-cli-app:latest
        # Add these options to suppress warnings
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: type=registry,ref=ghcr.io/${{ env.REPOSITORY_OWNER }}/weather-cli-app:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ env.REPOSITORY_OWNER }}/weather-cli-app:buildcache,mode=max